export const TRKMMV = {
  classData :[{'value' :'BA-1', 'Academic Fee':5100}, {'value' :'BA-2', 'Academic Fee':5100}, {'value' :'BA-3', 'Academic Fee':5100}],
  studentTypeData :[{value :'Regular'},{value :'Private'}, {value :'Ex'}, {value:'Single Subject'}],
  subjectData :[{value :'Hindi'},{value:'Sanskrit'}, {value:'Medieval History'}, {value:'Home Science'},{value:'Pedagogy'},{value:'Sociology'}, {value:'Political Science'}],
  feeTypeData :[{value :'Academic Fee'}],
  IncomeCat :[{value:'BA-1'},
      {value:'BA-2'},
      {value:'BA-3'},
      {value:'Scholarship Form'},
      {value:'Practicle File'},
      {value:'MLA\'s / MP\'s Fund'},
      {value:'Load / Credit'},
      {value:'Honourable People'},
      {value:'Chairman\'s Fund'},
      {value:'Others'}
  ],
  ExpenseCat :[{value:'PNB Patherwa'},
      {value:'Purwanchal Bank Patherwa'},
      {value:'Central Bank Tamkuhi'},
      {value:'Salary'},
      {value:'Examination'},
      {value:'Food'},
      {value:'Construction'},
      {value:'Maintainance'},
      {value:'University'},
      {value:'Challan'},
      {value:'Technology/Communication'},
      {value:'Stationary'},
      {value:'Oil'},
      {value:'Loan'},
      {value:'To Chairman'},
      {value:'Others'}
  ]
}
